# blender_manifest.toml
# Manifest file for the Blender Fast Start Extension

schema_version = "1.0.0"
id = "BL_FastStart" 
version = "1.8.6"

name = "BL Fast Start (MP4/MOV)"
author = "usrname0 (AI assisted)"
maintainer = "usrname0"
tagline = "A checkbox to add a 'Fast Start' copy of MP4/MOV renders"
type = "add-on"
license = ["GPL-3.0-or-later"]
# # Optional: required by some licenses.
copyright = [
    "2025 usrname0 (BL_FastStart)",
    "2008 - 2013 Daniel G. Taylor <dan@programmer-art.org> (qtfaststart)",
]


description = """Youtube recommends MP4 + moov atom at the front of the file (Fast Start).
This checkbox creates an extra MP4/MOV file with a custom suffix (default '-faststart'). 
Your normal render is untouched."""

website = "https://github.com/usrname0/BL_FastStart"
tags = ["Render", "User Interface"]
blender_version_min = "4.4.0"