# blender_manifest.toml
# Manifest file for the Blender Fast Start Extension

schema_version = "1.0.0"
id = "BL_FastStart" 
version = "1.9.2"

name = "BL Fast Start (MP4/MOV)"
tagline = "A checkbox to add a 'Fast Start' copy of MP4/MOV renders"
type = "add-on"

author = "usrname0"
maintainer = "usrname0"

website = "https://github.com/usrname0/BL_FastStart"

tags = ["Render", "User Interface"]

blender_version_min = "4.4.0"

license = ["SPDX:GPL-3.0-or-later"]

description = """Youtube recommends MP4 + moov atom at the front of the file (Fast Start).
This checkbox creates an extra MP4/MOV file with a custom suffix (default '-faststart'). 
Your normal render is untouched."""

copyright = [
    "2025 usrname0 (BL_FastStart)",
    "2008 - 2013 Daniel G. Taylor <dan@programmer-art.org> (qtfaststart)",
]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/.gitignore",
    "/README.md",
    "/*.zip",
    "examples/",
]