# blender_manifest.toml
# Manifest file for the Blender Fast Start Extension

schema_version = "1.0.0"
id = "blender_faststart" 
version = "1.8.1" 
name = "Fast Start (MP4/MOV)"
author = "usrname0 (plus AI)"
maintainer = "usrname0 (plus AI)"
tagline = "Makes a copy with moov atom at the front of the file (Fast Start)"
type = "add-on"
license = ["GPL-3.0-or-later"]
description = """Inserts a checkbox to add a 'Fast Start' copy to MP4/MOV renders.
Creates an extra MP4/MOV file with a custom suffix (default '-faststart'). Your normal render is untouched."""
website = "https://github.com/usrname0/blender_faststart"
tags = ["Render", "User Interface"]
blender_version_min = "4.4.0"